INSERT INTO [ONLAB].[dbo].[temp_fact_movies]
SELECT
      [movieId]
      ,[imdbId]
      ,[adult]
      ,[budget]
      ,[original_title]
      ,[popularity]
      ,[release_date]
      ,[revenue]
      ,[runtime]
      ,[tagline]
      ,[vote_average]
      ,[vote_count]
  FROM [ONLAB].[dbo].[movies]
